// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sexxhoqbgvbpybwmkxln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNleHhob3FiZ3ZicHlid21reGxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMjQ0MDgsImV4cCI6MjA2OTYwMDQwOH0.oSBHB29jtEv8eUOT45BOVSl4NFPvXCCKDfuF7FUSPBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});